src = [
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E10.mp4",
        "src1": "O8xAwSr0Je4oANrZOtZxZj84%2FqleABL5KUMe3v20LxnZCsXtlKPuOvT7%2BnoAyFzFu4ZP19aODSHc63ptQgGEjA%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP10 220628\u3010\u4e94\u671f\u8054\u5408\u00d7\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E10.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E11.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B929aCZBHO%2FMEWzjB33vIy%2B3yuoe84yy%2Fv3jFLzTdtaSfkSMwqCwX1AVCuv3XobfwA%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP11 220705\u3010\u4e94\u671f\u8054\u5408\u00d7\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E11.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E12.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B9Ali%2BYkmO2Qa%2Btc4D6eDGxqgAtNScW0foyUECCB7dNsdgK6iSmSsNIKZjmm8SLM4A%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP12 220712\u3010\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E12.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E13.mp4",
        "src1": "O8xAwSr0Je4oANrZOtZxZoZAaTKhv%2FkZmsBHeylK0jM4R2UGkhsTjxjpUzyQ3qNP%2BcvCvpze8FI5QqQomrUaDw%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP13 220719\u3010\u5c0f\u5ddd\u756a\u8304\u56ed\u00d7\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E13.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E14.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B2iY7D6D5qdb3QhzcFoP9W4hsCqYhokglLepzFWeg5RM%2FRK%2FuEwoo85lqKqepJZPNQ%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP14 220725\u3010\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E14.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E15.mp4",
        "src1": "O8xAwSr0Je4oANrZOtZxZjyXmXlX%2Bdv9%2FJGIvvr8vD0R%2Fzf27OiQWUfM2spy0RsMKwBcpORYgjuGmiVlssU%2BtQ%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP15 220802\u3010\u5948\u592e\u96ea\u7cd5\u5c4b\u00d7\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E15.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E16.mp4",
        "src1": "O8xAwSr0Je4oANrZOtZxZqdv4%2FI4qqzYCxiX5otCxTleoFbnI8MWVQvx3iSpIiLgHejzfjdRKmjq3kMZPF844w%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP16 220809\u3010\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E16.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E17.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B%2Fr0Y11SzyuonYbiwyIULdRD9%2F23GmVkITBOVEeHN5PNgU0U7Pq6%2B8Pc%2BWx2BX95gg%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP17 220816\u3010\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E17.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E18.mp4",
        "src1": "O8xAwSr0Je4oANrZOtZxZn3dPtNdLmaFF71qQwNJry86yNo9vl66lRqjmLdLCB7jx%2FiLt7ccHZJEaWFLMeLFHA%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP18 220823\u3010\u4e94\u671f\u8054\u5408\u00d7\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E18.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E19.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B1iYi7oGqx2QoTbvL9zq0LKUn6p7M2b68oeGQBztkez1PqhQDS5EOSkgi%2FQGmdtkPg%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP19 220830\u3010\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E19.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E20.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B1iYi7oGqx2QoTbvL9zq0LKiLF%2Ftjfyv5b9SsrwLXjP0yEWmODt9DCqEJ3f%2F3pl2RA%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP20 220906\u3010\u771f\u5fc3\u7f8e\u7a7a\u751c\u54c1\u5e97\u00d7\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E20.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E21.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B5QMWMxXBLV0to7pMlTDI5L2%2BAXkzHFTacnqNgKDpPdAzTTk%2Bhyaw%2FD8Ya184LPE%2BA%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP21 220913\u3010\u4e94\u671f\u8054\u5408\u00d7\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E21.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E22.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B0RSBvzp3Wr2bRgyHCNB4dxUJmVO%2FSBqY9BFmB%2B%2B%2Bin3GMw7NPhql8N8c4vfCU%2FtyA%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP22 220920\u3010\u5c0f\u5ddd\u756a\u8304\u56ed\u00d7\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E22.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E23.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B66k76pyalRccwCPfPZLDtS8VAotAryCBtac8aS3XMWwtc%2BA1yO3wdvc9UDeycgkew%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP23 220926\u3010\u706b\u67f4\u4ebaIroha\u00d7\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E23.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E24.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2BybEHZ0fJp8%2FCrZTTphd4UaIftC2%2FGTFh7Nl%2BL%2FSq63Ad2beebLUU164HwkL7ANmGw%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP24 221003\u3010\u5c0f\u5ddd\u756a\u8304\u56ed\u00d7\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E24.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E25.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B1jGTEcefpqd96DyRbt6vf15cQMkbhMts%2BXPzHshiTHHYC279AeGA74sagfPdbapTw%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP25 221011\u3010\u706b\u67f4\u4ebaIroha\u00d7\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E25.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E26.mp4",
        "src1": "O8xAwSr0Je4oANrZOtZxZpiLqtHULKUq9i7azi1JcZGPCNNljc2Q8qRW7Sh81KmbAKmwfcluTiFpz20gaaxk9g%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP26 221017\u3010\u706b\u67f4\u4ebaIroha\u00d7\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E26.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E27.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B9cYo0yrTNW%2BbWf7ZbrsZcNlvpA55FhTKsBSeW7jPqFWw6ma7Rn%2BwqK466Ylqoc3Ew%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP27 221024\u3010\u706b\u67f4\u4ebaIroha\u00d7\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E27.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E28.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B9cYo0yrTNW%2BbWf7ZbrsZcNgQTsjWwHVXVhMMMBHT7t5s%2FCFlTn5P2o2o%2Bok5CH3Nw%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP28 221031\u3010\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E28.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E29.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B6%2BxXxsiTBfmBW4QdOJ1fkcqEOq505iR1rdbjkyw5lf6svyqYMkHAd8nGmO2Xnen9Q%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP29 221108\u3010\u706b\u67f4\u4ebaIroha\u00d7\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E29.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E30.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B6%2BxXxsiTBfmBW4QdOJ1fkcDmlqxwCvQWd8nntrymgNwt8JmnQPqEXRs6AK3BBgPdA%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP30 221115\u3010\u706b\u67f4\u4ebaIroha\u00d7\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E30.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E31.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B4qVBmuu0Hvx2EjoX8gNULWUrr0g79%2FvHQ2XY1TMp76Kg6S%2ByAbjM%2BtXBqleBtXkiQ%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP31 221122\u3010\u706b\u67f4\u4ebaIroha\u00d7\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E31.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E32.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B1JSJiM%2FWMG006kIiXpLDtpejhGriqYwOCWgiwawwgRJyB4fj%2BCmvaCNiNUAbfWonQ%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP32 221129\u3010\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E32.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E33.mp4",
        "src1": "O8xAwSr0Je4oANrZOtZxZp6C6O7iKtrCfqSO%2BOls5sZaM5eUgNzpxqY0jzqtY48P1tdI%2BYlCbpMH6LETTn9d9w%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP33 221206\u3010\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E33.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E34.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B90Vtz6LZZ8%2B65F7G1KJVI1wp3qsd9lwcutI8ZfLk7XOGBje1%2F8xKLq8khQR6khziQ%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP34 221212\u3010\u706b\u67f4\u4ebairoha\u00d7\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E34.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E35.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B90Vtz6LZZ8%2B65F7G1KJVI0E73nGF50Y2%2FVrXHUQSthhNb6bneiIXFf%2BJxO5vAbwyg%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP35 221220\u3010\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E35.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
    {
        "src": "javascript:;",
        "src0": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E36.mp4",
        "src1": "oyQUDEJeuyWcl9GycrB4%2B4GKIButfadO53jv3RL%2BMLxwCh5nX37Hj89FclJbhMcScDmYm9tbUIsyD8DPfbHjaw%3D%3D",
        "src2": "teBkQ18QvPHDI",
        "src3": "",
        "title": "",
        "type": "video\/mp4",
        "caption": "\u7b2c3\u5b63 EP36 230110\u3010\u5c0f\u5ddd\u756a\u8304\u56ed\u00d7\u4e0a\u884c\u4e4b\u5742\u3011",
        "description": "",
        "image": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "thumb": {
            "src": "https:\/\/ddys.art\/wp-includes\/images\/media\/video.png",
            "width": 48,
            "height": 64,
        },
        "meta": {"length_formatted": ""},
        "portn": "9543",
        "srctype": "0",
        "cut": "0",
        "vttshift": "0",
        "userIP": "125.115.251.75",
        "subsrc": "\/v\/variety\/Nogi_Star\/Nogi_Star_S03E36.ddr",
        "dimensions": {
            "original": {"width": "300", "height": "200"},
            "resized": {"width": "600", "height": "400"},
        },
    },
]


# print(src)
import os
import subprocess
import json

# curl 'https://ddys.art/getvddr/video?id=nS2miQwEhgImy3R8UI5aEYgalSoOTsyZXW8rXtCj7od9UVmbP%2Fibuc4%2Bs9KZV8HQgQtEutI6fuxXYCEc%2FqEPPQ%3D%3D&dim=1080P&type=mix'    -H 'cookie: X_CACHE_KEY=70cd25512b9c097aba396a664202f71f; __cf_bm=F.i_uXxXqERfXe.4XyatCauz11VWS7D.zshRwZYDxd8-1680496844-0-ASnRgrUzC5EBpmEA0yFpGA7JnmFChQa3eRajnPz8/s9/TsOsEOdAzNbwm+4JTQaVPgq6ns+csZR23Vvolqk/AW8rkguBbJdK7Ds0MHDbHavBH6F8Ak7BcBpQg6q7zHCy3g=='   -H 'referer: https://ddys.art/the-night-agent/?ep=6'

for entry in src:
    # curl = f"curl    -H 'authority: ddys.art'   -H 'accept: */*'   -H 'accept-language: ja-JP,ja;q=0.9,en-US;q=0.8,en;q=0.7'   -H 'cookie: X_CACHE_KEY=70cd25512b9c097aba396a664202f71f; __cf_bm=O_5H5kCfM1NwpxRKK7QgkGs3QE4_kwLtsvTvobtmMg8-1680487478-0-AWmGUINi/h+Q7+25XWVF1d4S5aD/32LNPgLVNZ1tMYTFtGwDmpNf8TUcu7wRv+po+9dBQpM+QKHGtifb6cxulpvsDkTbuRROqF6spuR5vsVSbJo3ULX3LkDit4gI4CQURQ=='   -H 'dnt: 1'   -H 'referer: https://ddys.art/the-night-agent/?ep=2'   -H 'sec-ch-ua: \"Google Chrome\";v=\"111\", \"Not(A:Brand\";v=\"8\", \"Chromium\";v=\"111\"'   -H 'sec-ch-ua-mobile: ?0'   -H 'sec-ch-ua-platform: \"Windows\"'   -H 'sec-fetch-dest: empty'   -H 'sec-fetch-mode: cors'   -H 'sec-fetch-site: same-origin'   -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36'"
    # os.system(curl)
    # subprocess.run(curl, capture_output=True)
    print(entry["caption"])

    wants = ["23", "33"]
    for want in wants:
        if want in entry["src0"]:

            result = subprocess.run(
                [
                    "curl",
                    f"https://ddys.art/getvddr/video?id={entry['src1']}&dim=1080P&type=mix",
                    "-H",
                    "X_CACHE_KEY=6a6cd1e1479927593396dda8097099cd; __cf_bm=uPyZ6B0F.IbOXtHX7UxfBMlGGgdgmfBtnebHGTvy67E-1681365909-0-ARx6t2yR4fW/ngQV1psL4zsK8ejCRXaPhrBD2sf6cWfDYTgbhm125Xw7LfhOtf2srcVxxE5GkpCy4Y0v+wEEw7MFfV9n6HuIviE8zIC2GlRximcqzjGx6MRzVRPeodM0jw==",
                    "-H",
                    "referer:https://ddys.art/the-night-agent/?ep=10",
                ],
                stdout=subprocess.PIPE,
            )
            temp = json.loads(result.stdout.decode("utf-8"))
            print(temp["url"])
            subprocess.run(["curl", temp["url"], "-o", f'{entry["caption"]}.mp4'])
        #  os.system("sleep 10")
